config/routes.rb
Rails.application.routes.draw do
  root 'login#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :inquiry, only: [:index, :new, :edit]
  resources :users, only: [:index, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
# Inquiries Controller
class InquiriesController < ApplicationController
  def index
    @search = Inquiry.ransack(params[:q])
    @inquiries = @search.result
  end

  # def show
  # end

  def new
    @inquiry = Inquiry.new
  end

  def create
    p params
  end

  # def edit
  # end

  # def update
  # end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    p 'ログイン画面表示'
  end
end

app/controllers/users_controller.rb
# User Controller
class UsersController < ApplicationController
  def index
    @search = User.ransack(params[:q])
    @users = @search.result
  end

  # def show
  # end

  # def edit
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inquiries/edit.html.erb
<h1>Inquiries#edit</h1>
<p>Find me in app/views/inquiries/edit.html.erb</p>

app/views/inquiries/index.html.erb
<h1>Inquiries#index</h1>
<p>Find me in app/views/inquiries/index.html.erb</p>

<%= search_form_for @search, url: inquiry_index_path do |f| %>
  <%= f.label :comment, 'コメント' %>
  <%= f.search_field :comment_cont %>
  <%= f.submit '検索' %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link(@search, :comment) -%></th>
    </tr>
  </thead>
  <tbody>
    <% @inquiries.each do |inquiry| %>
    <tr>
      <td><%= inquiry.comment -%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/inquiries/new.html.erb
<%= form_with model: @inquiries, url: '/inquiry', local: true do |form| %>
  <div class="field">
    <%= form.label :'問合せ内容' %>
    <%= form.text_field :subject, id: :subject %>
  </div>

  <div class="field">
    <%= form.text_area :comtent, style: 'width: 360px' %>
  </div>

  <div class="field">
    <%= form.label :'チェック１' %>
    <%= form.check_box :checkbox_01, id: :checkbox_01 %>
    <%= form.label :'チェック２' %>
    <%= form.check_box :checkbox_02, id: :checkbox_02 %>
    <%= form.label :'チェック３' %>
    <%= form.check_box :checkbox_03, id: :checkbox_03 %>
  </div>

  <div class="field">
    <%= form.label :'ラジオ１' %>
    <%= form.radio_button :radio_button, id: :radio_button_01 %>
    <%= form.label :'ラジオ２' %>
    <%= form.radio_button :radio_button, id: :radio_button_02 %>
    <%= form.label :'ラジオ３' %>
    <%= form.radio_button :radio_button, id: :radio_button_03 %>
  </div>

  <div class="actions">
    <%= submit_tag "Save", id: 'submit' %>
  </div>
<% end %>

app/views/inquiries/show.html.erb
<h1>Inquiries#show</h1>
<p>Find me in app/views/inquiries/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<h1>LOGIN</h1>

<% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->
  <h4> mail： <%= current_user.email %> </h4>
  <%= link_to "Add Inquiry", new_inquiry_path, class: 'get' %> <!-- 問合せ画面に遷移する -->
  <%= link_to "Logout", destroy_user_session_path, method: :delete %> <!-- ログアウトする -->
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
  <h2> Not logged in </h2>
  <%= link_to "Login", new_user_session_path, class: 'post' %> <!-- ログイン画面に遷移する -->
  <%= link_to "Sign up", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に遷移する -->
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%= search_form_for @search, url: users_path do |f| %>
  <%= f.label :name, '名前' %>
  <%= f.search_field :name_cont %>
  <%= f.submit '検索' %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link(@search, :name) -%></th>
      <th><%= sort_link(@search, :email) -%></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name -%></td>
      <td><%= user.email -%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>